# Permalinks
permalink: pretty

# Setup
title: Matt Smith
tagline: "Web Dev | Front-End Engineer | UX Designer"
url: "https://allthingssmitty.com"
brand: &brand_name
  allthingssmitty
paginate: 3
baseurl: ""
description: "Matt Smith is a Maine-based application developer who builds solutions to deliver engaging user experiences."
analytics_id: UA-55352436-3
ga4Id: G-B17534YEJY
timezone: America/New_York

# Assets
assets:
  compress:
    css: sass
    js: uglifier
  autoprefixer:
    browsers: ["> 1%"]
  plugins:
    css:
      autoprefixer: {}
  sass:
    sass_dir: _sass
    style: ":compressed"

# About/contact
author:
  name: Matt Smith
  codepen: ["https://codepen.io/", *brand_name]
  github: ["https://github.com/", *brand_name]
  linkedin: ["https://linkedin.com/in/", *brand_name]
  twitter: ["https://twitter.com/", *brand_name]

# Custom vars and plugins
version: 2.0.0
github:
  repo: 'https://github.com/allthingssmitty/allthingssmitty.github.io'
plugins:
  - jekyll-paginate
  #- jekyll-autoprefixer

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true