# Permalinks
permalink: pretty

# Setup
paginate: 3
baseurl: ""
timezone: America/New_York

# Assets
assets:
  compress:
    css: sass
    js: uglifier
  autoprefixer:
    browsers: ["> 1%"]
  plugins:
    css:
      autoprefixer: {}
  sass:
    sass_dir: _sass
    style: ":compressed"

# Custom vars and plugins
version: 2.0.0
github:
  repo: 'https://github.com/allthingssmitty/allthingssmitty.github.io'
plugins:
  - jekyll-paginate
  #- jekyll-autoprefixer

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true