# Permalinks
permalink:          pretty

# Setup
title:              Matt Smith
tagline:            Web Dev, Front-End Engineer, UX Designer
url:                https://allthingssmitty.com
brand:              allthingssmitty
paginate:           3
baseurl:            ""

# Site
description:        Matt Smith is a Maine-based web developer who builds applications to deliver engaging user interactions and experiences.

# Google analytics
analytics_id:       UA-55352436-3

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:         _sass
  style:            :compressed

timezone:           America/New_York

# About/contact
author:
  name:             Matt Smith
  url:              https://allthingssmitty.com
  codepen:          https://codepen.io/allthingssmitty
  github:           https://github.com/allthingssmitty
  linkedin:         https://linkedin.com/in/allthingssmitty
  twitter:          https://twitter.com/allthingssmitty
  follow_me_on:     Follow me on
  share_on:         Share on

# Custom vars
version:            1.0.0
github:
  repo:             https://github.com/allthingssmitty/allthingssmitty.github.io

autoprefixer:
  browsers:
  - last 2 versions

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-autoprefixer
